# Generated by Django 3.2.6 on 2021-08-25 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='ClinicReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('reservation_time', models.TimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_clinic', to='clinic.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
    ]
